version: 2.1

orbs:
  auto: auto/release@0.2.3

jobs:
  build:
    docker:
      - image: "cimg/node:16.10.0"
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # Fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install
          command: yarn install
      - run:
          name: build
          command: yarn build
      - auto/shipit
workflows:
  version: 2
  main:
    jobs:
      - build:
          context: npm-deploy
          filters:
            branches:
              only:
                - main
